* Моделювання процесів за допомогою модифікованих клітинних автоматів
** Вступ
** Модифікація клітинних автоматів
*** Огляд клітинних автоматів
Вперше клітинні автомати були запропоновані у 1940-50-х роках в роботах фон
Неймана та Улама[1]. Проте наступні 30 років такий тип автоматів не дуже
цікавив дослідників. У 1970-х Конвей запропонував так звану Гру Життя (Game of
Life) - двовимірний клітинний автомат, що описувався простим набором правил,
проте генерував напрочуд цікаво поведінку. В 1980-х глибоким дослідженням
одновимірних клітинних автоматів займався Стівен Вольфрам, зокрема він
запропонував їх класифікацію.

Клітинні автомати - особливий клас дискретних динамічних систем, дискретними в
яких є час, простір та множина станів. Зазвичай клітинний автомат
представляється як об'єднання однакових комірок (клітин), з'єднаних між
собою. Разом клітини утворюють так звану клітинну решітку (форма якої може
бути різноманітною). Клітина виступає скінченним автоматом, стан якого на
кроці /t+1/ визначається станом системи (а саме сусідів та самої клітини) на
попередньому кроці /t/ та набором локальних правил взаємодії сусідніх
клітин. Рідше під час визначення стану використовуються глобальні правила -
такі, що визначають вплив певної загальної змінної на всі клітини автомату.[2]
Саме розширення такими глобальними правилами буде досліджено у даній роботі.

На кожному кроці кожна клітина приймає один із станів з наявної скінченної
множини станів /S/, котре може розглядатись як /k/-вимірний алфавіт /S/ = {0,
1, ..., k-1}.

Якщо кожна клітина має /2r/ сусідів, локальне правило переходу виглядає
наступним чином /ϕ : S^{2r+1} → S/. Правило може бути детермінованим або
стохастичним.

Для визначення сусідів конкретної клітини у двовимірному автоматі існує
декілька підходів, найпопулярніші з яких "сусідство" фон Неймана та
"сусідство" Мура[3]. Перший розглядає лише чотири клітини, котрі безпосередньо
торкаються поточної клітини (згори, знизу, зліва та справа). А другий підхід
додає до цих чотирьох ще чотири клітини, що знаходяться на діагоналях відносно
поточної клітини. Надалі буде розглядатись підхід Мура, тому правило переходу
можна записати наступним чином /a_{i,j}^{(t+1)} = ϕ(a_{i,j}^{(t)},
a_{i,j+1}^{(t)}, a_{i+1,j}^{(t)}, a_{i+1,j+1}^{(t)}, a_{i,j-1}^{(t)},
a_{i-1,j}^{(t)}, a_{i-1,j-1}^{(t)}, a_{i-1,j+1}^{(t)},
a_{i+1,j-11}^{(t)})/.

Так як автомат представляє собою обмежену сітку, постає проблема визначення
сусідів клітин, котрі знаходяться на межах цієї сітки. Одним з
найпопулярніших шляхів розв'язання проблеми є використання тороїдальної
структури сітки - якщо клітина немає сусіда згори, цим сусідом виступає
клітина на відповідній позиції знизу сітки, аналогічно відбувається "перехід"
для інших клітин на межах.

Ітеративний процес роботи автомату полягає у тому, що на кожному кроці
наведена вище функція застосовується до кожної клітини водночас. Тобто, кожна
клітина оброблюється паралельно та незалежно, що робить клітинні автомати
гарним інструментом моделювання процесів зі схожою паралельною структурою,
наприклад, економічної взаємодії.

Зазвичай клітинні автомати у пам'яті комп'ютера представляються як масиви
комірок, де кожна комірка відповідає певній клітині автомата. Водночас
більшість автоматів описується в термінах певної підмножини "живих" станів та
визначення сусідів клітин ("мертві" клітини можуть бути вираховані
користуючись цією інформацією). Тому такий автомат можливо представити просто
як множину "живих" клітин.[4] Саме такий варіант представлення (дещо
модифікований для конкретних задач) використовувався у роботі.
*** Розширення керуючим інформаційним каналом
*** Розширення вихідним інформаційним каналом
*** Використання модифікованого автомату для розпізнавання необмеженої граматики
** Модель економічних відносин
*** Опис моделі
*** Загальна структура клітинного автомату
*** Використання керуючого та вихідного каналів
** Візуалізація клітинних автоматів
*** React та ідея virtual DOM
*** ClojureScript та Om
*** Communicating Sequential Processes та core.async
*** Огляд виконаної реалізації
** Висновки
** Список літератури
1. Клеточные автоматы. Реализация и эксперименты - Лев Наумов, Анатолий Шалыто
2. Modelling the Spatial Dimension of Economic Systems with Cellular
   Automata - Max Keilbach
3. https://en.wikipedia.org/wiki/Cellular_automaton
4. Clojure Programming - Chas Emerick, Brian Carper, Christophe Grand
